server:
  port: 8080
  servlet:
    context-path: /

elasticsearch:
  host: 192.168.31.106
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500

logging:
  level.root: info
