server:
  port: 8080
  servlet:
    context-path: /

spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200   #ES的连接地址，多个地址用逗号分隔
#      username: ---用户名
#      password: ---密码
      connection-timeout: 1000           #连接超时时间
      read-timeout: 1000
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: localhost:9300

logging:
  level.root: info
