server:
  port: 8080
kafka:
  topic: demo-lua

# \u914D\u7F6EKafka
spring:
  kafka:
    bootstrap-servers: 192.168.1.121:9090,192.168.1.121:9091,192.168.1.121:9092
      # producer:   # \u914D\u7F6E\u751F\u4EA7\u8005
    # key-serializer: org.apache.kafka.common.serialization.StringSerializer
    # value-serializer: org.apache.kafka.common.serialization.StringSerializer

#    consumer:   # \u914D\u7F6E\u6D88\u8D39\u8005
#      group-id: demoGroupTest  # \u6D88\u8D39\u8005\u7EC4
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer




